version: '3'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - minio
      - clickhouse

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio123"
    ports:
      - "9000:9000"
    command: server /data

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9001:9000"
    environment:
      CLICKHOUSE_DB: "default"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: ""
